name: liquidhaskell-tutorial
version: '0.2.0.0'
synopsis: Source for "Programming with Refinement Types"
category: Web
author: Ranjit Jhala
maintainer: jhala@cs.ucsd.edu
copyright: Ranjit Jhala
license: MIT
homepage: https://github.com/ucsd-progsys/liquidhaskell-tutorial
extra-source-files:
- README.md
dependencies:
- liquid-base
- liquid-vector
- liquid-containers
- liquid-bytestring
- liquidhaskell

library:
  ghc-options: -fdefer-type-errors -fplugin=LiquidHaskell

  source-dirs:
    - src

  exposed-modules:
    - Main
